### ISSUE TITLE
Support file extension-based highlighting

### ISSUE THREAD

**Issue by phaazon** [phaazon/kak-tree-sitter#20]
Currently, highlighting request are made by sending the content of `%opt{filetype}`. This works for most cases, but not all of them. For instance, `sh` vs. `bash`.

It would be great to also support file extensions. The big question is: if we use file extension, do we want to always use it? It doesn’t seem unlikely that a user would like to override the content a buffer to highlight it differently.

**Comment by korreman** [comment]
Extensions aren't necessarily accurate. Using your example, most bash scripts use the `.sh` extension or no extension at all.

The underlying problem to solve here is accurate filetype detection. Maybe a better solution is to roll your own separate detection, using [`file`](https://linux.die.net/man/1/file) for instance, and write the result to an option `%opt{kts_filetype}` which can then be read. You could also let that option default to `%opt{filetype}` if the new detector fails.

**Comment by phaazon** [comment]
That’s a good point. But I would rather not introduce that logic in kts as it’s not _really_ the scope of the project. What I’m doing in my own configuration is using hooks to set `filetype` to whatever I want based on filenames / extensions. I’m probably going to roll the wiki like that at first.

@taupiqueur you had concerns about that. What do you think?

**Comment by korreman** [comment]
Letting language detection stay out of scope would be understandable. In that case, I still suggest supporting an override option like `kts_language` instead of changing `filetype`. Other plugins and scripts might depend on `filetype` and break if it's changed.

Interestingly, tree-sitter itself does support language detection using [a pretty smart approach](https://tree-sitter.github.io/tree-sitter/syntax-highlighting#language-detection). No grammars seem to provide `first-line-regex` or `content-regex` in their `package.json` though. This can be implemented externally if needed.

**Comment by korreman** [comment]
Another case for proper detection somewhere in the toolchain:  there are several assembly dialects that all use the extensions `.asm` and `.s`. These are all categorized as GAS by Kakoune. Some form of language detection is needed to correctly highlight them.

**Comment by phaazon** [comment]
Yeah, I like that `kts_lang` thing. But who would set it, though?

**Comment by korreman** [comment]
How about if KTS prefers to read `kts_lang`, but falls back to filetype if the former isn't set?
The user can then set `kts_lang` in those cases where `filetype` is wrong or too unspecific.

Someone wanting sophisticated filetype detection could write their own engine which interfaces with KTS through the variable.
If it later turns out that detection should be incorporated into KTS,
it's still useful to expose the chosen grammar as a variable and let the user override it.

Aside: Maybe `kts_grammar` would be better? There could be multiple grammars for the same language after all.

**Comment by phaazon** [comment]
This should now be fixed by #96. I’ll update the wiki to explain how to customize the detection.
