### ISSUE TITLE
PID detection doesn't allways work

### ISSUE THREAD

**Issue by phaazon** [phaazon/kak-tree-sitter#81]
We often end up with many KTS running. This is mostly due to the cleanup option I think. We should probably check whether `kak-tree-sitter` is in the return of `ps` in addition to checking the PID file value.

**Comment by korreman** [comment]
Checking if the returned process is actually `kak-tree-sitter` is a good idea, but that would allow more instances to open rather than fewer.

The current check treats `ps` failing in any way as "no running instance". The bug might occur because `ps` sometimes fails in another way?

A different approach to detecting current instances might be to check the status of the socket by attempting to open and ping the current server. Even if any previous instance is already running, it would then be best to kill it.

**Comment by phaazon** [comment]
Should be fixed now.
